Sprint 1/step 1
dqrest/learning-data-base pull request #1
Opened 2023-07-04 18:10 UTC by Valer1yaaa

add theory "BD and DBMS.docx"

2023-07-07 13:42 UTC, dqrest requested changes
Замечания приведены в сносках файла.

2023-07-07 13:42 UTC, dqrest commented on theory/BD and DBMS.docx
Замечания приведены в сносках файла.
[BD and DBMS.docx](https://github.com/dqrest/learning-data-base/files/11982553/BD.and.DBMS.docx)

2023-07-07 17:11 UTC, Valer1yaaa commented on theory/BD and DBMS.docx
@dqrest были внесены правки.

2023-07-08 07:01 UTC, dqrest commented on theory/BD and DBMS.docx
Замечательно!

2023-07-08 07:03 UTC, dqrest approved these changes

2023-07-09 09:27 UTC, merged