Sprint 2/step 2
dqrest/learning-data-base pull request #4
Opened 2023-07-24 16:31 UTC by Valer1yaaa

**Добавлено:**
+ Инструкция по установке SQLite, PostgreSQL;
+ Инструкция по созданию таблиц;
+ Код по созданию таблиц на SQLite.

2023-07-29 08:30 UTC, Valer1yaaa commented
**Добавлено:**
+ Инструкция по удалению и изменению таблиц.

2023-08-01 13:49 UTC, dqrest commented on db/create_table/sqlite/code.txt
DB Browser for SQLite сможет открыть файл с расширением .txt и выполнить скрипт? Если нет, то нужно выложить скрипт создания таблиц с расширением, поддерживаемым DB Browser for SQLite?

2023-08-01 13:51 UTC, dqrest requested changes
Поменять расширение файла db/create_table/sqlite/code.txt на расширение, поддерживаемое DB Browser for SQLite.

2023-08-02 19:20 UTC, Valer1yaaa commented
@dqrest, DB Browser for SQLite нормально работает с текстовыми файлами. На всякий случай добавлено code.sql.

2023-08-07 05:43 UTC, merged

2023-08-07 05:56 UTC, dqrest reviewed
Все хорошо